/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package college.course.project;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author mattw
 */
public class Courses extends javax.swing.JFrame {
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form Courses
     */
    public Courses() {
        initComponents();
        conn = Database.java_db();
        this.getContentPane().setBackground(Color.blue);
        updateTable();
        fillCombo();
        currentDateAndTime();
        txt_username.setText(College.username);
    }
    
    private void updateTable() {
        String sql = "SELECT * FROM course ORDER BY term, course_name";
        
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            table_course.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void fillCombo() {
        String sql = "SELECT DISTINCT term FROM course";
        
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            
            while (rs.next()) {
                String term = rs.getString("term");
                combo_term.addItem(term);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void currentDateAndTime() {
        Calendar calendar = new GregorianCalendar();
        int month = calendar.get(Calendar.MONTH);
        int day = calendar.get(Calendar.DAY_OF_MONTH);
        int year = calendar.get(Calendar.YEAR);
        menu_date.setText((month + 1) + "/" + day + "/" + year);
        
        Date date = new Date();
        SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
        menu_time.setText(s.format(date));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane3 = new javax.swing.JLayeredPane();
        txt_credits = new javax.swing.JTextField();
        txt_remainingseats = new javax.swing.JTextField();
        lbl_coursename = new javax.swing.JLabel();
        txt_coursename = new javax.swing.JTextField();
        lbl_seats = new javax.swing.JLabel();
        lbl_remainingseats = new javax.swing.JLabel();
        txt_seats = new javax.swing.JTextField();
        lbl_credits = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_course = new javax.swing.JTable();
        lbl_welcome = new javax.swing.JLabel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        txt_search = new javax.swing.JTextField();
        combo_term = new javax.swing.JComboBox<>();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        btn_print = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_drop = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        slider_credits = new javax.swing.JSlider();
        btn_submit = new javax.swing.JButton();
        txt_username = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_students = new javax.swing.JMenu();
        item_schedule = new javax.swing.JMenuItem();
        item_transcript = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        item_logout = new javax.swing.JMenuItem();
        item_close = new javax.swing.JMenuItem();
        menu_date = new javax.swing.JMenu();
        menu_time = new javax.swing.JMenu();
        menu_help = new javax.swing.JMenu();
        item_help = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Class", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jLayeredPane3.setForeground(new java.awt.Color(255, 255, 255));

        txt_credits.setEditable(false);

        txt_remainingseats.setEditable(false);

        lbl_coursename.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_coursename.setForeground(new java.awt.Color(255, 255, 255));
        lbl_coursename.setText("Course Name");

        txt_coursename.setEditable(false);

        lbl_seats.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_seats.setForeground(new java.awt.Color(255, 255, 255));
        lbl_seats.setText("Seats");

        lbl_remainingseats.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_remainingseats.setForeground(new java.awt.Color(255, 255, 255));
        lbl_remainingseats.setText("Remaining Seats");

        txt_seats.setEditable(false);

        lbl_credits.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbl_credits.setForeground(new java.awt.Color(255, 255, 255));
        lbl_credits.setText("Credits");

        jLayeredPane3.setLayer(txt_credits, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txt_remainingseats, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lbl_coursename, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txt_coursename, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lbl_seats, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lbl_remainingseats, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txt_seats, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(lbl_credits, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(lbl_remainingseats)
                        .addGap(18, 18, 18)
                        .addComponent(txt_remainingseats))
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_coursename)
                            .addComponent(lbl_credits)
                            .addComponent(lbl_seats))
                        .addGap(47, 47, 47)
                        .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_credits, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_seats)
                            .addComponent(txt_coursename))))
                .addContainerGap())
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_coursename)
                    .addComponent(txt_coursename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_credits)
                    .addComponent(txt_credits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_seats)
                    .addComponent(txt_seats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_remainingseats)
                    .addComponent(txt_remainingseats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table_course.setBackground(java.awt.Color.blue);
        table_course.setForeground(new java.awt.Color(255, 255, 255));
        table_course.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_courseMouseClicked(evt);
            }
        });
        table_course.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                table_courseKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(table_course);

        lbl_welcome.setForeground(new java.awt.Color(255, 255, 255));
        lbl_welcome.setText("Feel free to register for any courses!");

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Class", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        txt_search.setBackground(java.awt.Color.green);
        txt_search.setToolTipText("Enter Course");
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        combo_term.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                combo_termPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLayeredPane4.setLayer(txt_search, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(combo_term, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                .addComponent(combo_term, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_search)
                .addContainerGap())
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_term, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLayeredPane5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buttons", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        btn_print.setBackground(java.awt.Color.black);
        btn_print.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_print.setForeground(new java.awt.Color(255, 255, 255));
        btn_print.setText("Print");
        btn_print.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        btn_clear.setBackground(java.awt.Color.black);
        btn_clear.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_clear.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear.setText("Clear");
        btn_clear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_drop.setBackground(java.awt.Color.black);
        btn_drop.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_drop.setForeground(new java.awt.Color(255, 255, 255));
        btn_drop.setText("Drop");
        btn_drop.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btn_drop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dropActionPerformed(evt);
            }
        });

        btn_add.setBackground(java.awt.Color.black);
        btn_add.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("Add");
        btn_add.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        jLayeredPane5.setLayer(btn_print, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(btn_clear, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(btn_drop, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(btn_add, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_drop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_print, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_drop))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_print)
                    .addComponent(btn_clear))
                .addContainerGap())
        );

        jLayeredPane6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Credits", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        slider_credits.setForeground(new java.awt.Color(255, 255, 255));
        slider_credits.setMajorTickSpacing(1);
        slider_credits.setMaximum(4);
        slider_credits.setMinimum(1);
        slider_credits.setMinorTickSpacing(1);
        slider_credits.setPaintLabels(true);
        slider_credits.setPaintTicks(true);
        slider_credits.setSnapToTicks(true);

        btn_submit.setBackground(java.awt.Color.black);
        btn_submit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_submit.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit.setText("Submit");
        btn_submit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        jLayeredPane6.setLayer(slider_credits, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane6.setLayer(btn_submit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addComponent(slider_credits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(slider_credits, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btn_submit))
        );

        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setText("jLabel18");

        menu_students.setText("Students");

        item_schedule.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        item_schedule.setText("Class Schedule");
        item_schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_scheduleActionPerformed(evt);
            }
        });
        menu_students.add(item_schedule);

        item_transcript.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        item_transcript.setText("Unofficial Transcript");
        item_transcript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_transcriptActionPerformed(evt);
            }
        });
        menu_students.add(item_transcript);
        menu_students.add(jSeparator1);

        item_logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        item_logout.setText("Logout");
        item_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_logoutActionPerformed(evt);
            }
        });
        menu_students.add(item_logout);

        item_close.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        item_close.setText("Close");
        item_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_closeActionPerformed(evt);
            }
        });
        menu_students.add(item_close);

        jMenuBar1.add(menu_students);

        menu_date.setText("Date");
        jMenuBar1.add(menu_date);

        menu_time.setText("Time");
        jMenuBar1.add(menu_time);

        menu_help.setText("Help");

        item_help.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        item_help.setText("Help");
        item_help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_helpActionPerformed(evt);
            }
        });
        menu_help.add(item_help);

        jMenuBar1.add(menu_help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_welcome)
                .addGap(18, 18, 18)
                .addComponent(txt_username)
                .addContainerGap(1112, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLayeredPane3)
                        .addComponent(jLayeredPane4)
                        .addComponent(jLayeredPane5)
                        .addComponent(jLayeredPane6))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(649, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_welcome)
                    .addComponent(txt_username))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(1481, 772));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void item_scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_scheduleActionPerformed
        Schedule schedule = new Schedule();
        schedule.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_item_scheduleActionPerformed

    private void item_helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_helpActionPerformed
        try {
            Desktop desktop = Desktop.getDesktop();
            if (desktop.isSupported(Desktop.Action.OPEN)) {
                desktop.open(new File("C:\\Users\\mattw\\OneDrive\\Documents\\How to Apply for a Course.pdf"));
            } else {
                JOptionPane.showMessageDialog(null, "Open is not supported", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (HeadlessException | IOException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_item_helpActionPerformed

    private void table_courseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_courseMouseClicked
        String id = table_course.getValueAt(table_course.getSelectedRow(), 0).toString();
        String course_name = table_course.getValueAt(table_course.getSelectedRow(), 1).toString();
        String course_short = table_course.getValueAt(table_course.getSelectedRow(), 2).toString();
        String credits = table_course.getValueAt(table_course.getSelectedRow(), 3).toString();
        String seats = table_course.getValueAt(table_course.getSelectedRow(), 4).toString();
        String remaining_seats = table_course.getValueAt(table_course.getSelectedRow(), 5).toString();
        String term = table_course.getValueAt(table_course.getSelectedRow(), 6).toString();
        College.course_id = Integer.parseInt(id);
        College.remaining_seats = Integer.parseInt(remaining_seats);

        txt_coursename.setText(course_name);
        txt_credits.setText(credits);
        txt_seats.setText(seats);
        txt_remainingseats.setText(remaining_seats);

    }//GEN-LAST:event_table_courseMouseClicked

    private void table_courseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_table_courseKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN) {
            String id = table_course.getValueAt(table_course.getSelectedRow(), 0).toString();
            String course_name = table_course.getValueAt(table_course.getSelectedRow(), 1).toString();
            String course_short = table_course.getValueAt(table_course.getSelectedRow(), 2).toString();
            String credits = table_course.getValueAt(table_course.getSelectedRow(), 3).toString();
            String seats = table_course.getValueAt(table_course.getSelectedRow(), 4).toString();
            String remaining_seats = table_course.getValueAt(table_course.getSelectedRow(), 5).toString();
            String term = table_course.getValueAt(table_course.getSelectedRow(), 6).toString();
            College.course_id = Integer.parseInt(id);
            College.remaining_seats = Integer.parseInt(remaining_seats);

            txt_coursename.setText(course_name);
            txt_credits.setText(credits);
            txt_seats.setText(seats);
            txt_remainingseats.setText(remaining_seats);
        }
    }//GEN-LAST:event_table_courseKeyReleased

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        String tmp = txt_search.getText();
        String sql = "SELECT * FROM course WHERE course_name = ? or course_short = ?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, tmp);
            pst.setString(2, tmp);
            rs = pst.executeQuery();

            if (rs.next()) {
                String course_name = rs.getString("course_name");
                txt_coursename.setText(course_name);
                int credits = rs.getInt("credits");
                txt_credits.setText(String.valueOf(credits));
                int seats = rs.getInt("seats");
                txt_seats.setText(String.valueOf(seats));
                int remaining_seats = rs.getInt("remaining_seats");
                txt_remainingseats.setText(String.valueOf(remaining_seats));
                College.course_id = rs.getInt("course_id");
                College.remaining_seats = rs.getInt("remaining_seats");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void combo_termPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_combo_termPopupMenuWillBecomeInvisible
        String tmp = (String)combo_term.getSelectedItem();
        String sql = "SELECT * FROM course WHERE term = ?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, tmp);
            rs = pst.executeQuery();
            table_course.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_combo_termPopupMenuWillBecomeInvisible

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        String sql = "INSERT INTO schedule (student_id, course_id, credits) VALUES (?, ?, ?)";
        String sql2 = "UPDATE course SET remaining_seats = ? WHERE course_id = ?";
        
        if (College.remaining_seats == 0) {
                JOptionPane.showMessageDialog(null, "Class is full!", "No Seats Left", JOptionPane.ERROR_MESSAGE);
        } else {
            
            try {
            
                pst = conn.prepareStatement(sql);
                pst.setInt(1, College.student_id);
                pst.setInt(2, College.course_id);
                pst.setInt(3, Integer.parseInt(txt_credits.getText()));
                pst.execute();

                College.remaining_seats = College.remaining_seats - 1;
                pst = conn.prepareStatement(sql2);
                pst.setInt(1, College.remaining_seats);
                pst.setInt(2, College.course_id);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Course added to schedule!", "Add Course", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "You are already in this class!", "Already In Class", JOptionPane.ERROR_MESSAGE);
            } finally {
                try {
                    rs.close();
                    pst.close();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        updateTable();
        
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        
        String sql;

        switch (slider_credits.getValue()) {
            case 1:
            sql = "SELECT * FROM course WHERE credits = 1";
            break;
            case 2:
            sql = "SELECT * FROM course WHERE credits = 2";
            break;
            case 3:
            sql = "SELECT * FROM course WHERE credits = 3";
            break;
            default:
            sql = "SELECT * FROM course WHERE credits = 4";
            break;
        }

        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            table_course.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void item_transcriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_transcriptActionPerformed
        Transcript transcript = new Transcript();
        transcript.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_item_transcriptActionPerformed

    private void btn_dropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dropActionPerformed
        
        String sql = "DELETE FROM schedule WHERE student_id = ? and course_id = ?";
        
        String sql2 = "UPDATE course SET remaining_seats = ? WHERE course_id = ?";
        
        try {
            int sure = JOptionPane.showConfirmDialog(null, "Do you really want to delete this course?", "Delete Course?", JOptionPane.YES_NO_OPTION);
            if (sure == JOptionPane.YES_OPTION) {
                pst = conn.prepareStatement(sql);
                pst.setInt(1, College.student_id);
                pst.setInt(2, College.course_id);
                int deleted = pst.executeUpdate();
                if (deleted == 0) {
                JOptionPane.showMessageDialog(null, "Nothing to delete!", "Nothing to Delete", JOptionPane.ERROR_MESSAGE);
                return;
                }
            
                College.remaining_seats = College.remaining_seats + 1;
                pst = conn.prepareStatement(sql2);
                pst.setInt(1, College.remaining_seats);
                pst.setInt(2, College.course_id);
                pst.execute();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                pst.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        updateTable();
    }//GEN-LAST:event_btn_dropActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        txt_coursename.setText("");
        txt_credits.setText("");
        txt_seats.setText("");
        txt_remainingseats.setText("");
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        MessageFormat header = new MessageFormat("List of Courses");
        
        MessageFormat footer = new MessageFormat("Page{0, number, integer}");
        
        try {
            table_course.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_printActionPerformed

    private void item_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_logoutActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_item_logoutActionPerformed

    private void item_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_item_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Courses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Courses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Courses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Courses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Courses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_drop;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> combo_term;
    private javax.swing.JMenuItem item_close;
    private javax.swing.JMenuItem item_help;
    private javax.swing.JMenuItem item_logout;
    private javax.swing.JMenuItem item_schedule;
    private javax.swing.JMenuItem item_transcript;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lbl_coursename;
    private javax.swing.JLabel lbl_credits;
    private javax.swing.JLabel lbl_remainingseats;
    private javax.swing.JLabel lbl_seats;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JMenu menu_date;
    private javax.swing.JMenu menu_help;
    private javax.swing.JMenu menu_students;
    private javax.swing.JMenu menu_time;
    private javax.swing.JSlider slider_credits;
    private javax.swing.JTable table_course;
    private javax.swing.JTextField txt_coursename;
    private javax.swing.JTextField txt_credits;
    private javax.swing.JTextField txt_remainingseats;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_seats;
    private javax.swing.JLabel txt_username;
    // End of variables declaration//GEN-END:variables
}
